# -*- coding: utf-8 -*-
"""xtract insights from sales data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10au3PtHr9FDfnHzctR3D1UuqY0z_QnMy

# 1. Project Title
"""

# ============================================
# 📊 E-commerce Sales Data Analysis Project
# Author: Hafiz Ahmad Adil
# Goal: Extract insights from sales data
# ============================================

"""# 2. Import Libraries"""

import pandas as pd
import matplotlib.pyplot as plt

"""# 3. Mount Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""# 4. Load Dataset"""

# Pandas Lecture 2 - Pandas Basics
df = pd.read_csv("/content/drive/MyDrive/pandas/ecommerce_sales_data.csv")

"""# 5. Initial Data Exploration"""

# Preview Data
df.head()

# Structure of Dataset
df.info()

# Statistical summary
df.describe()

"""# 6. Revenue Analysis by Category"""

# Revenue by Category
# Which product category earns the most money?
category_revenue = df.groupby("Category")["Revenue"].sum()

print(category_revenue)

# sorting for better understanding
category_revenue_sorted = df.groupby("Category")["Revenue"].sum().sort_values(ascending=False)
print(category_revenue_sorted)

# Visualization
category_revenue.plot(kind='bar', title="Revenue by Category")
plt.ylabel("Revenue")
plt.show()

# Category with highest revenue
top_category = category_revenue.idxmax()
print(f"🔥 Top Revenue Category: {top_category}")

"""# 7. Regional Performance Analysis"""

# Compare Regions
# Which region is performing best?
region_performance = df.groupby("Region")[["Revenue", "Profit"]].sum()

print(region_performance)

# Sort by Revenue (Best Region First)
df.groupby("Region")[["Revenue", "Profit"]].sum().sort_values(by="Revenue", ascending=False)

# Sort by Profit (Better Business Decision)
df.groupby("Region")[["Revenue", "Profit"]].sum().sort_values(by="Profit", ascending=False)

# Visualization
region_performance.plot(kind='bar', title="Region-wise Revenue & Profit")
plt.show()

best_region = region_performance["Revenue"].idxmax()
print(f"🌍 Best Performing Region: {best_region}")

"""# 8. Correlation Analysis"""

correlation_matrix = df.corr(numeric_only=True)

print(correlation_matrix)

"""Does Ad Spend increase Revenue?
Is Units Sold strongly related?
"""

# Which factors drive revenue most?
df[['Revenue','Ad_Spend','Units_Sold']].corr()

"""I performed correlation analysis to identify relationships between variables. I found that revenue is strongly correlated with profit and moderately with units sold, while ad spend and customer ratings show negligible impact.

# 📈 9. Top Performing Records
"""

top_sales = df.sort_values(by="Revenue", ascending=False).head()

print(top_sales)
print("🏆 Highest revenue transaction identified")

"""# 📦 10. Outlier Detection"""

df['Revenue'].plot.box(title="Revenue Distribution")
plt.show()

""" # 🧠 11. Final Business Insights (MOST IMPORTANT 🚨)"""

print("📊 KEY INSIGHTS:")

print(f"1. Top Category: {category_revenue.idxmax()}")
print(f"2. Best Region: {region_performance['Revenue'].idxmax()}")

corr = df[['Revenue','Ad_Spend']].corr().iloc[0,1]
print(f"3. Ad Spend vs Revenue Correlation: {round(corr,2)}")

